/** Course-spec reconstruction: direct mentor-review route; mirrors required lesson behaviors while remaining separate from the Signal Ledger public portfolio index. */
import { ArrowUp, Code2, ExternalLink, Github, Mail } from "lucide-react";

const technologies = [
  ["HTML", "#e44d26", "5"], ["CSS", "#264de4", "#"], ["JavaScript", "#f0db4f", "JS"], ["TypeScript", "#3178c6", "TS"],
  ["Vue", "#42b883", "V"], ["Nuxt", "#00dc82", "N"], ["React", "#61dafb", "◌"], ["State", "#7c52ca", "∞"],
];

const projects = [
  ["Commerce practice", "HTML, CSS, JavaScript", "A course-spec card interaction that demonstrates project content, hover overlay, and external-link affordances.", "from-[#c2a58d] via-[#2a2830] to-[#e8d3a8]"],
  ["Dashboard practice", "HTML, CSS, JavaScript", "A course-spec card interaction that demonstrates responsive hierarchy, contrast, and project-description visibility.", "from-[#202c45] via-[#647fc1] to-[#cbd0dd]"],
  ["Portfolio practice", "HTML, CSS, JavaScript", "A course-spec card interaction that demonstrates the required page sections, navigation anchors, and mobile rules.", "from-[#6e47b1] via-[#d8caee] to-[#221c3c]"],
];

export default function CoursePortfolio() {
  return (
    <main className="min-h-screen bg-white font-[Lato,Arial,sans-serif] text-[#242424]">
      <aside className="bg-[#fff2dd] px-5 py-3 text-center font-mono text-[11px] leading-5 text-[#492f21]">COURSE-SPEC RECONSTRUCTION · Direct mentor-review route · Separate from the Signal Ledger public portfolio</aside>
      <section id="about" className="flex min-h-screen flex-col">
        <nav className="mx-auto flex h-[100px] w-full max-w-[1000px] items-center justify-between px-4"><a href="#about" className="text-2xl font-black text-[#6030b1]">Course Portfolio</a><div className="flex items-center gap-6 text-sm font-bold"><a className="hover:text-[#6030b1]" href="#languages">Languages</a><a className="hover:text-[#6030b1]" href="#projects">Projects</a><a className="rounded-full bg-[#6030b1] px-5 py-2 text-white hover:bg-[#5d3eff]" href="mailto:student@example.com">Contact</a></div></nav>
        <div className="mx-auto grid w-full max-w-[900px] flex-1 items-center gap-10 px-5 pb-12 md:grid-cols-[1fr_.74fr]">
          <div className="text-center"><div className="mx-auto mb-7 grid h-[108px] w-[108px] place-items-center rounded-full border-[5px] border-white bg-[radial-gradient(circle_at_35%_30%,#dbccf9_0_14%,#6030b1_15%_46%,#242424_47%)] text-xl font-bold text-white shadow-[0_8px_16px_rgba(0,0,0,.16)]">CP</div><h1 className="text-4xl font-bold leading-tight">Hey! I’m <span className="text-[#6030b1]">Course Student</span> <span className="inline-block animate-[pulse_1s_ease-in-out_infinite]">👋</span></h1><p className="mx-auto mt-4 max-w-[590px] text-xl leading-relaxed">I’m a frontend developer learning to build responsive web applications with clear hierarchy, purposeful interactions, and useful user experiences.</p><div className="mt-7 flex justify-center gap-6"><a aria-label="Course project source placeholder" href="#projects"><Github /></a><a aria-label="Technology stack" href="#languages"><Code2 /></a><a aria-label="Email course student" href="mailto:student@example.com"><Mail /></a><a aria-label="Course résumé section" href="#footer">▣</a></div></div>
          <div className="relative min-h-[310px] overflow-hidden rounded-[20px] bg-gradient-to-br from-[#ece4ff] to-[#f5f2fb]"><div className="absolute inset-x-7 bottom-9 top-11 rotate-[-5deg] rounded-lg border border-[#c8b8ea] bg-white shadow-[0_20px_35px_rgba(96,48,177,.18)]"><div className="flex gap-1 border-b border-[#e4e0ec] p-3"><i className="h-2 w-2 rounded-full bg-[#6030b1]"/><i className="h-2 w-2 rounded-full bg-[#e3d9f5]"/><i className="h-2 w-2 rounded-full bg-[#e3d9f5]"/></div><div className="grid grid-cols-[1.2fr_.8fr] gap-3 p-4"><div className="row-span-2 min-h-28 rounded bg-gradient-to-br from-[#6030b1] to-[#a98bde]"/><div className="h-14 rounded bg-[#f0ebfa]"/><div className="h-14 rounded bg-[#f0ebfa]"/><div className="h-14 rounded bg-[#f0ebfa]"/><div className="h-14 rounded bg-[#f0ebfa]"/></div></div><div className="absolute bottom-6 right-3 rotate-[5deg] rounded bg-[#242424] px-4 py-3 font-mono text-sm font-bold text-white shadow-xl">&lt;build /&gt;</div></div>
        </div>
      </section>
      <section id="languages" className="bg-[#f8f8f8] py-14"><div className="mx-auto max-w-[800px] px-4"><h2 className="mb-6 text-center text-4xl font-bold">This is my <span className="text-[#6030b1]">technology stack</span></h2><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4">{technologies.map(([name, color, mark]) => <article className="group relative grid min-h-[156px] place-items-center" key={name}><div style={{ backgroundColor: color }} className={`grid h-[90px] w-[90px] place-items-center rounded-[22px] text-2xl font-black text-white transition group-hover:scale-90 group-hover:brightness-75 ${name === "JavaScript" ? "text-[#3c3c3c]" : ""}`}>{mark}</div><strong className="absolute bottom-3 scale-0 text-lg opacity-0 transition-all group-hover:scale-100 group-hover:opacity-100">{name}</strong></article>)}</div></div></section>
      <section id="projects" className="py-14"><div className="mx-auto max-w-[800px] px-4"><h2 className="mb-8 text-center text-4xl font-bold">Here are some of my <span className="text-[#6030b1]">projects</span></h2><div className="grid gap-16">{projects.map(([title, stack, description, background]) => <article className="group relative min-h-[360px] overflow-hidden rounded-[20px] shadow-[0_20px_80px_rgba(0,0,0,.45)]" key={title}><div className={`absolute inset-0 grid place-items-center bg-gradient-to-br ${background} font-mono text-3xl font-black tracking-[.08em] text-white transition duration-500 group-hover:scale-105 group-hover:blur-[5px]`}>{title.split(" ")[0].toUpperCase()}</div><div className="absolute inset-0 flex translate-y-full flex-col justify-center bg-[#1c1d25]/80 px-8 text-white opacity-0 transition duration-500 group-hover:translate-y-0 group-hover:opacity-100 sm:px-[90px]"><h3 className="text-4xl font-bold leading-tight">{title}</h3><h4 className="mt-3 font-bold">{stack}</h4><p className="mt-4 max-w-[520px] leading-relaxed">{description}</p><div className="mt-4 flex gap-5"><a aria-label={`Source placeholder for ${title}`} href="#projects"><Github /></a><a aria-label={`Live placeholder for ${title}`} href="#projects"><ExternalLink /></a></div></div></article>)}</div></div></section>
      <footer id="footer" className="flex flex-col items-center justify-center bg-[#242424] px-4 py-20 text-white"><a className="group relative mb-6 grid h-[70px] w-[70px] place-items-center rounded-full bg-[#6030b1] text-3xl" href="#about">⌂<span className="absolute left-20 top-6 whitespace-nowrap text-sm font-bold opacity-0 transition group-hover:translate-x-3 group-hover:opacity-100">Top <ArrowUp className="inline" size={14} /></span></a><div className="mb-7 flex w-full max-w-[500px] justify-around text-sm font-bold"><a href="#projects">GitHub</a><a href="#languages">LinkedIn</a><a href="mailto:student@example.com">Email</a><a href="#about">Résumé</a></div><small>Private course-spec study reconstruction</small></footer>
    </main>
  );
}
